// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/author_service.proto

package author

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorCatalog_GetAuthor_FullMethodName      = "/authorservice.AuthorCatalog/GetAuthor"
	AuthorCatalog_CreateAuthor_FullMethodName   = "/authorservice.AuthorCatalog/CreateAuthor"
	AuthorCatalog_ListAuthors_FullMethodName    = "/authorservice.AuthorCatalog/ListAuthors"
	AuthorCatalog_GetAuthorBooks_FullMethodName = "/authorservice.AuthorCatalog/GetAuthorBooks"
)

// AuthorCatalogClient is the client API for AuthorCatalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorCatalogClient interface {
	GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error)
	CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*CreateAuthorResponse, error)
	ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (*ListAuthorsResponse, error)
	GetAuthorBooks(ctx context.Context, in *GetAuthorBooksRequest, opts ...grpc.CallOption) (*GetAuthorBooksResponse, error)
}

type authorCatalogClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorCatalogClient(cc grpc.ClientConnInterface) AuthorCatalogClient {
	return &authorCatalogClient{cc}
}

func (c *authorCatalogClient) GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorResponse)
	err := c.cc.Invoke(ctx, AuthorCatalog_GetAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorCatalogClient) CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*CreateAuthorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuthorResponse)
	err := c.cc.Invoke(ctx, AuthorCatalog_CreateAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorCatalogClient) ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (*ListAuthorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthorsResponse)
	err := c.cc.Invoke(ctx, AuthorCatalog_ListAuthors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorCatalogClient) GetAuthorBooks(ctx context.Context, in *GetAuthorBooksRequest, opts ...grpc.CallOption) (*GetAuthorBooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthorBooksResponse)
	err := c.cc.Invoke(ctx, AuthorCatalog_GetAuthorBooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorCatalogServer is the server API for AuthorCatalog service.
// All implementations must embed UnimplementedAuthorCatalogServer
// for forward compatibility.
type AuthorCatalogServer interface {
	GetAuthor(context.Context, *GetAuthorRequest) (*GetAuthorResponse, error)
	CreateAuthor(context.Context, *CreateAuthorRequest) (*CreateAuthorResponse, error)
	ListAuthors(context.Context, *ListAuthorsRequest) (*ListAuthorsResponse, error)
	GetAuthorBooks(context.Context, *GetAuthorBooksRequest) (*GetAuthorBooksResponse, error)
	mustEmbedUnimplementedAuthorCatalogServer()
}

// UnimplementedAuthorCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorCatalogServer struct{}

func (UnimplementedAuthorCatalogServer) GetAuthor(context.Context, *GetAuthorRequest) (*GetAuthorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthor not implemented")
}
func (UnimplementedAuthorCatalogServer) CreateAuthor(context.Context, *CreateAuthorRequest) (*CreateAuthorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthor not implemented")
}
func (UnimplementedAuthorCatalogServer) ListAuthors(context.Context, *ListAuthorsRequest) (*ListAuthorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuthors not implemented")
}
func (UnimplementedAuthorCatalogServer) GetAuthorBooks(context.Context, *GetAuthorBooksRequest) (*GetAuthorBooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthorBooks not implemented")
}
func (UnimplementedAuthorCatalogServer) mustEmbedUnimplementedAuthorCatalogServer() {}
func (UnimplementedAuthorCatalogServer) testEmbeddedByValue()                       {}

// UnsafeAuthorCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorCatalogServer will
// result in compilation errors.
type UnsafeAuthorCatalogServer interface {
	mustEmbedUnimplementedAuthorCatalogServer()
}

func RegisterAuthorCatalogServer(s grpc.ServiceRegistrar, srv AuthorCatalogServer) {
	// If the following call panics, it indicates UnimplementedAuthorCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorCatalog_ServiceDesc, srv)
}

func _AuthorCatalog_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorCatalogServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorCatalog_GetAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorCatalogServer).GetAuthor(ctx, req.(*GetAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorCatalog_CreateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorCatalogServer).CreateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorCatalog_CreateAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorCatalogServer).CreateAuthor(ctx, req.(*CreateAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorCatalog_ListAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorCatalogServer).ListAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorCatalog_ListAuthors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorCatalogServer).ListAuthors(ctx, req.(*ListAuthorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorCatalog_GetAuthorBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorCatalogServer).GetAuthorBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorCatalog_GetAuthorBooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorCatalogServer).GetAuthorBooks(ctx, req.(*GetAuthorBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorCatalog_ServiceDesc is the grpc.ServiceDesc for AuthorCatalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorCatalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authorservice.AuthorCatalog",
	HandlerType: (*AuthorCatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthor",
			Handler:    _AuthorCatalog_GetAuthor_Handler,
		},
		{
			MethodName: "CreateAuthor",
			Handler:    _AuthorCatalog_CreateAuthor_Handler,
		},
		{
			MethodName: "ListAuthors",
			Handler:    _AuthorCatalog_ListAuthors_Handler,
		},
		{
			MethodName: "GetAuthorBooks",
			Handler:    _AuthorCatalog_GetAuthorBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/author_service.proto",
}
