// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/author_service.proto

package author

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	BirthYear     int32                  `protobuf:"varint,4,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_proto_author_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Author) GetBirthYear() int32 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *Author) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_proto_author_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthorRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorResponse) Reset() {
	*x = GetAuthorResponse{}
	mi := &file_proto_author_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorResponse) ProtoMessage() {}

func (x *GetAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	BirthYear     int32                  `protobuf:"varint,3,opt,name=birth_year,json=birthYear,proto3" json:"birth_year,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_proto_author_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAuthorRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateAuthorRequest) GetBirthYear() int32 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *CreateAuthorRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type CreateAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorResponse) Reset() {
	*x = CreateAuthorResponse{}
	mi := &file_proto_author_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorResponse) ProtoMessage() {}

func (x *CreateAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthorResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_proto_author_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuthorsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuthorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_proto_author_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *ListAuthorsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAuthorBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      int32                  `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorBooksRequest) Reset() {
	*x = GetAuthorBooksRequest{}
	mi := &file_proto_author_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorBooksRequest) ProtoMessage() {}

func (x *GetAuthorBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorBooksRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorBooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuthorBooksRequest) GetAuthorId() int32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type BookSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	PublishedYear int32                  `protobuf:"varint,4,opt,name=published_year,json=publishedYear,proto3" json:"published_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSummary) Reset() {
	*x = BookSummary{}
	mi := &file_proto_author_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSummary) ProtoMessage() {}

func (x *BookSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSummary.ProtoReflect.Descriptor instead.
func (*BookSummary) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{8}
}

func (x *BookSummary) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookSummary) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookSummary) GetPublishedYear() int32 {
	if x != nil {
		return x.PublishedYear
	}
	return 0
}

type GetAuthorBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Books         []*BookSummary         `protobuf:"bytes,2,rep,name=books,proto3" json:"books,omitempty"`
	BookCount     int32                  `protobuf:"varint,3,opt,name=book_count,json=bookCount,proto3" json:"book_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorBooksResponse) Reset() {
	*x = GetAuthorBooksResponse{}
	mi := &file_proto_author_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorBooksResponse) ProtoMessage() {}

func (x *GetAuthorBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_author_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorBooksResponse.ProtoReflect.Descriptor instead.
func (*GetAuthorBooksResponse) Descriptor() ([]byte, []int) {
	return file_proto_author_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuthorBooksResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *GetAuthorBooksResponse) GetBooks() []*BookSummary {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *GetAuthorBooksResponse) GetBookCount() int32 {
	if x != nil {
		return x.BookCount
	}
	return 0
}

var File_proto_author_service_proto protoreflect.FileDescriptor

const file_proto_author_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/author_service.proto\x12\rauthorservice\"w\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x04 \x01(\x05R\tbirthYear\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"B\n" +
	"\x11GetAuthorResponse\x12-\n" +
	"\x06author\x18\x01 \x01(\v2\x15.authorservice.AuthorR\x06author\"t\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"birth_year\x18\x03 \x01(\x05R\tbirthYear\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"E\n" +
	"\x14CreateAuthorResponse\x12-\n" +
	"\x06author\x18\x01 \x01(\v2\x15.authorservice.AuthorR\x06author\"E\n" +
	"\x12ListAuthorsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\\\n" +
	"\x13ListAuthorsResponse\x12/\n" +
	"\aauthors\x18\x01 \x03(\v2\x15.authorservice.AuthorR\aauthors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"4\n" +
	"\x15GetAuthorBooksRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\x05R\bauthorId\"p\n" +
	"\vBookSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12%\n" +
	"\x0epublished_year\x18\x04 \x01(\x05R\rpublishedYear\"\x98\x01\n" +
	"\x16GetAuthorBooksResponse\x12-\n" +
	"\x06author\x18\x01 \x01(\v2\x15.authorservice.AuthorR\x06author\x120\n" +
	"\x05books\x18\x02 \x03(\v2\x1a.authorservice.BookSummaryR\x05books\x12\x1d\n" +
	"\n" +
	"book_count\x18\x03 \x01(\x05R\tbookCount2\xed\x02\n" +
	"\rAuthorCatalog\x12N\n" +
	"\tGetAuthor\x12\x1f.authorservice.GetAuthorRequest\x1a .authorservice.GetAuthorResponse\x12W\n" +
	"\fCreateAuthor\x12\".authorservice.CreateAuthorRequest\x1a#.authorservice.CreateAuthorResponse\x12T\n" +
	"\vListAuthors\x12!.authorservice.ListAuthorsRequest\x1a\".authorservice.ListAuthorsResponse\x12]\n" +
	"\x0eGetAuthorBooks\x12$.authorservice.GetAuthorBooksRequest\x1a%.authorservice.GetAuthorBooksResponseB\"Z task5-microservices/proto/authorb\x06proto3"

var (
	file_proto_author_service_proto_rawDescOnce sync.Once
	file_proto_author_service_proto_rawDescData []byte
)

func file_proto_author_service_proto_rawDescGZIP() []byte {
	file_proto_author_service_proto_rawDescOnce.Do(func() {
		file_proto_author_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_author_service_proto_rawDesc), len(file_proto_author_service_proto_rawDesc)))
	})
	return file_proto_author_service_proto_rawDescData
}

var file_proto_author_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_author_service_proto_goTypes = []any{
	(*Author)(nil),                 // 0: authorservice.Author
	(*GetAuthorRequest)(nil),       // 1: authorservice.GetAuthorRequest
	(*GetAuthorResponse)(nil),      // 2: authorservice.GetAuthorResponse
	(*CreateAuthorRequest)(nil),    // 3: authorservice.CreateAuthorRequest
	(*CreateAuthorResponse)(nil),   // 4: authorservice.CreateAuthorResponse
	(*ListAuthorsRequest)(nil),     // 5: authorservice.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),    // 6: authorservice.ListAuthorsResponse
	(*GetAuthorBooksRequest)(nil),  // 7: authorservice.GetAuthorBooksRequest
	(*BookSummary)(nil),            // 8: authorservice.BookSummary
	(*GetAuthorBooksResponse)(nil), // 9: authorservice.GetAuthorBooksResponse
}
var file_proto_author_service_proto_depIdxs = []int32{
	0, // 0: authorservice.GetAuthorResponse.author:type_name -> authorservice.Author
	0, // 1: authorservice.CreateAuthorResponse.author:type_name -> authorservice.Author
	0, // 2: authorservice.ListAuthorsResponse.authors:type_name -> authorservice.Author
	0, // 3: authorservice.GetAuthorBooksResponse.author:type_name -> authorservice.Author
	8, // 4: authorservice.GetAuthorBooksResponse.books:type_name -> authorservice.BookSummary
	1, // 5: authorservice.AuthorCatalog.GetAuthor:input_type -> authorservice.GetAuthorRequest
	3, // 6: authorservice.AuthorCatalog.CreateAuthor:input_type -> authorservice.CreateAuthorRequest
	5, // 7: authorservice.AuthorCatalog.ListAuthors:input_type -> authorservice.ListAuthorsRequest
	7, // 8: authorservice.AuthorCatalog.GetAuthorBooks:input_type -> authorservice.GetAuthorBooksRequest
	2, // 9: authorservice.AuthorCatalog.GetAuthor:output_type -> authorservice.GetAuthorResponse
	4, // 10: authorservice.AuthorCatalog.CreateAuthor:output_type -> authorservice.CreateAuthorResponse
	6, // 11: authorservice.AuthorCatalog.ListAuthors:output_type -> authorservice.ListAuthorsResponse
	9, // 12: authorservice.AuthorCatalog.GetAuthorBooks:output_type -> authorservice.GetAuthorBooksResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_author_service_proto_init() }
func file_proto_author_service_proto_init() {
	if File_proto_author_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_author_service_proto_rawDesc), len(file_proto_author_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_author_service_proto_goTypes,
		DependencyIndexes: file_proto_author_service_proto_depIdxs,
		MessageInfos:      file_proto_author_service_proto_msgTypes,
	}.Build()
	File_proto_author_service_proto = out.File
	file_proto_author_service_proto_goTypes = nil
	file_proto_author_service_proto_depIdxs = nil
}
