// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: simple.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum type
type BookGenre int32

const (
	BookGenre_UNKNOWN    BookGenre = 0
	BookGenre_FICTION    BookGenre = 1
	BookGenre_NONFICTION BookGenre = 2
	BookGenre_SCIFI      BookGenre = 3
	BookGenre_FANTASY    BookGenre = 4
	BookGenre_MYSTERY    BookGenre = 5
)

// Enum value maps for BookGenre.
var (
	BookGenre_name = map[int32]string{
		0: "UNKNOWN",
		1: "FICTION",
		2: "NONFICTION",
		3: "SCIFI",
		4: "FANTASY",
		5: "MYSTERY",
	}
	BookGenre_value = map[string]int32{
		"UNKNOWN":    0,
		"FICTION":    1,
		"NONFICTION": 2,
		"SCIFI":      3,
		"FANTASY":    4,
		"MYSTERY":    5,
	}
)

func (x BookGenre) Enum() *BookGenre {
	p := new(BookGenre)
	*p = x
	return p
}

func (x BookGenre) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookGenre) Descriptor() protoreflect.EnumDescriptor {
	return file_simple_proto_enumTypes[0].Descriptor()
}

func (BookGenre) Type() protoreflect.EnumType {
	return &file_simple_proto_enumTypes[0]
}

func (x BookGenre) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookGenre.Descriptor instead.
func (BookGenre) EnumDescriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{0}
}

// Simple message type
type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Hobbies       []string               `protobuf:"bytes,4,rep,name=hobbies,proto3" json:"hobbies,omitempty"` // Array/slice
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_simple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Person) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

// Message with nested type
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	ZipCode       int32                  `protobuf:"varint,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_simple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetZipCode() int32 {
	if x != nil {
		return x.ZipCode
	}
	return 0
}

type PersonWithAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Person        *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonWithAddress) Reset() {
	*x = PersonWithAddress{}
	mi := &file_simple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonWithAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonWithAddress) ProtoMessage() {}

func (x *PersonWithAddress) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonWithAddress.ProtoReflect.Descriptor instead.
func (*PersonWithAddress) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{2}
}

func (x *PersonWithAddress) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *PersonWithAddress) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// Message using enum
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Genre         BookGenre              `protobuf:"varint,4,opt,name=genre,proto3,enum=example.BookGenre" json:"genre,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_simple_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_simple_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_simple_proto_rawDescGZIP(), []int{3}
}

func (x *Book) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetGenre() BookGenre {
	if x != nil {
		return x.Genre
	}
	return BookGenre_UNKNOWN
}

func (x *Book) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Book) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_simple_proto protoreflect.FileDescriptor

const file_simple_proto_rawDesc = "" +
	"\n" +
	"\fsimple.proto\x12\aexample\"^\n" +
	"\x06Person\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\ahobbies\x18\x04 \x03(\tR\ahobbies\"j\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\x05R\azipCode\"h\n" +
	"\x11PersonWithAddress\x12'\n" +
	"\x06person\x18\x01 \x01(\v2\x0f.example.PersonR\x06person\x12*\n" +
	"\aaddress\x18\x02 \x01(\v2\x10.example.AddressR\aaddress\"\xa2\x01\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12(\n" +
	"\x05genre\x18\x04 \x01(\x0e2\x12.example.BookGenreR\x05genre\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable*Z\n" +
	"\tBookGenre\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aFICTION\x10\x01\x12\x0e\n" +
	"\n" +
	"NONFICTION\x10\x02\x12\t\n" +
	"\x05SCIFI\x10\x03\x12\v\n" +
	"\aFANTASY\x10\x04\x12\v\n" +
	"\aMYSTERY\x10\x05B\x17Z\x15protocolBuffers/protob\x06proto3"

var (
	file_simple_proto_rawDescOnce sync.Once
	file_simple_proto_rawDescData []byte
)

func file_simple_proto_rawDescGZIP() []byte {
	file_simple_proto_rawDescOnce.Do(func() {
		file_simple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simple_proto_rawDesc), len(file_simple_proto_rawDesc)))
	})
	return file_simple_proto_rawDescData
}

var file_simple_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_simple_proto_goTypes = []any{
	(BookGenre)(0),            // 0: example.BookGenre
	(*Person)(nil),            // 1: example.Person
	(*Address)(nil),           // 2: example.Address
	(*PersonWithAddress)(nil), // 3: example.PersonWithAddress
	(*Book)(nil),              // 4: example.Book
}
var file_simple_proto_depIdxs = []int32{
	1, // 0: example.PersonWithAddress.person:type_name -> example.Person
	2, // 1: example.PersonWithAddress.address:type_name -> example.Address
	0, // 2: example.Book.genre:type_name -> example.BookGenre
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_simple_proto_init() }
func file_simple_proto_init() {
	if File_simple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simple_proto_rawDesc), len(file_simple_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_simple_proto_goTypes,
		DependencyIndexes: file_simple_proto_depIdxs,
		EnumInfos:         file_simple_proto_enumTypes,
		MessageInfos:      file_simple_proto_msgTypes,
	}.Build()
	File_simple_proto = out.File
	file_simple_proto_goTypes = nil
	file_simple_proto_depIdxs = nil
}
