// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float32                `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float32                `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "add", "subtract", "multiply", "divide"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRequest) Reset() {
	*x = CalculateRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRequest) ProtoMessage() {}

func (x *CalculateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalculateRequest) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *CalculateRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type CalculateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateResponse) Reset() {
	*x = CalculateResponse{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateResponse) ProtoMessage() {}

func (x *CalculateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateResponse.ProtoReflect.Descriptor instead.
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CalculateResponse) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type SquareRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        float32                `protobuf:"fixed32,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SquareRootRequest) Reset() {
	*x = SquareRootRequest{}
	mi := &file_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquareRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRootRequest) ProtoMessage() {}

func (x *SquareRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRootRequest.ProtoReflect.Descriptor instead.
func (*SquareRootRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *SquareRootRequest) GetNumber() float32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SquareRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float32                `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SquareRootResponse) Reset() {
	*x = SquareRootResponse{}
	mi := &file_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquareRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRootResponse) ProtoMessage() {}

func (x *SquareRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRootResponse.ProtoReflect.Descriptor instead.
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SquareRootResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{4}
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calculations  []string               `protobuf:"bytes,1,rep,name=calculations,proto3" json:"calculations,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryResponse) GetCalculations() []string {
	if x != nil {
		return x.Calculations
	}
	return nil
}

func (x *HistoryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\"L\n" +
	"\x10CalculateRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x02R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x02R\x01b\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"I\n" +
	"\x11CalculateResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"+\n" +
	"\x11SquareRootRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x02R\x06number\",\n" +
	"\x12SquareRootResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x02R\x06result\"\x10\n" +
	"\x0eHistoryRequest\"K\n" +
	"\x0fHistoryResponse\x12\"\n" +
	"\fcalculations\x18\x01 \x03(\tR\fcalculations\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xea\x01\n" +
	"\n" +
	"Calculator\x12H\n" +
	"\tCalculate\x12\x1c.calculator.CalculateRequest\x1a\x1d.calculator.CalculateResponse\x12K\n" +
	"\n" +
	"SquareRoot\x12\x1d.calculator.SquareRootRequest\x1a\x1e.calculator.SquareRootResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.calculator.HistoryRequest\x1a\x1b.calculator.HistoryResponseB\rZ\vtask2/protob\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_calculator_proto_goTypes = []any{
	(*CalculateRequest)(nil),   // 0: calculator.CalculateRequest
	(*CalculateResponse)(nil),  // 1: calculator.CalculateResponse
	(*SquareRootRequest)(nil),  // 2: calculator.SquareRootRequest
	(*SquareRootResponse)(nil), // 3: calculator.SquareRootResponse
	(*HistoryRequest)(nil),     // 4: calculator.HistoryRequest
	(*HistoryResponse)(nil),    // 5: calculator.HistoryResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Calculate:input_type -> calculator.CalculateRequest
	2, // 1: calculator.Calculator.SquareRoot:input_type -> calculator.SquareRootRequest
	4, // 2: calculator.Calculator.GetHistory:input_type -> calculator.HistoryRequest
	1, // 3: calculator.Calculator.Calculate:output_type -> calculator.CalculateResponse
	3, // 4: calculator.Calculator.SquareRoot:output_type -> calculator.SquareRootResponse
	5, // 5: calculator.Calculator.GetHistory:output_type -> calculator.HistoryResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
